CREATE STREAM ksql_payments WITH (KAFKA_TOPIC='payments', VALUE_FORMAT='AVRO');

CREATE TABLE warnings
AS SELECT userId, COUNT(*)
FROM ksql_payments
WINDOW HOPPING(SIZE 10 MINUTES, ADVANCE BY 1 MINUTE)
GROUP BY userId
HAVING COUNT(*) > 5;